FROM python:3.9.13 as review-tool-base

ENV PIPENV_VENV_IN_PROJECT: true

WORKDIR /code

RUN apt-get update
RUN pip install pipenv


COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock
RUN pipenv install

COPY . .

EXPOSE 8000

CMD ["pipenv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
